USE master
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'MyAGDB1') 
	DROP DATABASE MyAGDB1
GO
--create database and insert records
CREATE DATABASE MyAGDB1
GO
ALTER DATABASE MyAGDB1 SET RECOVERY FULL
GO
USE [MyAGDB1]
CREATE TABLE t1 (c1 INT)
GO

INSERT INTO MyAGDB1.dbo.t1 VALUES (1)
INSERT INTO MyAGDB1.dbo.t1 VALUES (2)
SELECT * FROM MyAGDB1.dbo.t1
GO